package builder.map.util;


public class AlgorithmData {

    public AlgorithmData() {
        anInt6 = 4096;
        anInt7 = 16;
        anInt8 = 258;
        anInt9 = 23;
        anInt10 = 0;
        anInt11 = 1;
        anInt12 = 6;
        anInt13 = 50;
        anInt14 = 4;
        anInt6 = 4096;
        anInt7 = 16;
        anInt8 = 258;
        anInt9 = 23;
        anInt10 = 0;
        anInt11 = 1;
        anInt12 = 6;
        anInt13 = 50;
        anInt14 = 4;
        anInt15 = 18002;
        anInt17 = 0;
        anInt22 = 0;
        anIntArray36 = new int[256];
        anIntArray38 = new int[257];
        anIntArray39 = new int[257];
        aBoolArray42 = new boolean[256];
        aBoolArray43 = new boolean[16];
        aByteArray44 = new byte[256];
        aByteArray45 = new byte[4096];
        anIntArray46 = new int[16];
        aByteArray47 = new byte[anInt15];
        aByteArray48 = new byte[anInt15];
        aByteArrayArray49 = new byte[6][258];
        anIntArrayArray50 = new int[6][258];
        anIntArrayArray51 = new int[6][258];
        anIntArrayArray52 = new int[6][258];
        anIntArray53 = new int[6];
    }

    public int anInt6;
    public int anInt7;
    public int anInt8;
    public int anInt9;
    public int anInt10;
    public int anInt11;
    public int anInt12;
    public int anInt13;
    public int anInt14;
    public int anInt15;
    public byte aByteArray16[];
    public int anInt17;
    public int anInt18;
    public int anInt19;
    public int anInt20;
    public byte aByteArray21[];
    public int anInt22;
    public int anInt23;
    public int anInt24;
    public int anInt25;
    public byte aByte26;
    public int anInt27;
    public boolean aBool28;
    public int anInt29;
    public int anInt30;
    public int anInt31;
    public int anInt32;
    public int anInt33;
    public int anInt34;
    public int anInt35;
    public int anIntArray36[];
    public int anInt37;
    public int anIntArray38[];
    public int anIntArray39[];
    public static int anIntArray40[];
    public int anInt41;
    public boolean aBoolArray42[];
    public boolean aBoolArray43[];
    public byte aByteArray44[];
    public byte aByteArray45[];
    public int anIntArray46[];
    public byte aByteArray47[];
    public byte aByteArray48[];
    public byte aByteArrayArray49[][];
    public int anIntArrayArray50[][];
    public int anIntArrayArray51[][];
    public int anIntArrayArray52[][];
    public int anIntArray53[];
    public int anInt54;
}
